[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.build]
cmds = [
  "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
  "php artisan config:clear",
  "php artisan route:clear"
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
]
