[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-interaction"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"